### ISSUE TITLE
Where can we pass the beamer config object ?

### ISSUE THREAD

**Issue by Aarbel** [reenan/react-beamer#9]
Cf https://www.getbeamer.com/blog/tutorial-how-to-use-beamer-in-your-website-or-app

![image](https://user-images.githubusercontent.com/25119847/130425254-24715e86-1cec-4462-920e-c7fc5612b34c.png)

**Comment by Aarbel** [comment]
I mean, this part is quite confusing in your code: 

![image](https://user-images.githubusercontent.com/25119847/130429778-ca38f7c9-08d4-4f29-ba59-e000560bea11.png)

Whee do `args` come from ?

**Comment by reenan** [comment]
If you want to read the code, I'd suggest looking into `src` folder, and not the parsed one ;)

Here you can see the signature for [beamerInitialize](https://github.com/reenan/react-beamer/blob/master/src/beamerInitialize/index.js#L1).

[Here you can see the component definition](https://github.com/reenan/react-beamer/blob/master/src/BeamerHelmet/index.js#L8) if you want to use this version.

If you are using the function directly, you can do:

```
beamerInitialize(id, false, args) // false is needed to by-pass the URL attribute
```

If you are going with the component, then just pass it as prop:

```
<BeamerHelmet ... args={args} />
```

**Comment by Aarbel** [comment]
Thanks @reenan, maybe a short info in readme would be helpfull
